services:
  postgres:
    image: docker.io/postgres:12.5
    environment:
      POSTGRES_USER: migrator
      POSTGRES_PASSWORD: rotargim
    command:
      - postgres
      - -c
      - fsync=off
    ports:
      # forward port 5543 to avoid conflicting with normal postgres
      - 5543:5432
